version: "2"

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3

checks:
  method-complexity:
    enabled: true
    config:
      threshold: 10
  argument-count:
    enabled: false
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 250

exclude_patterns:
  - "*"
  - "!genomepy/*"
  - "genomepy/cli.py"
