repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --check
          - --recursive
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
          - --ignore-init-module-imports
          - setup.py
          - genomepy/
          - tests/

  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
        args:
          - --check
          - --profile=black
          - --conda-env=environment.yml
          - setup.py
          - genomepy/
          - tests/

  - repo: https://github.com/ambv/black
    rev: 21.5b2
    hooks:
    - id: black
      args:
        - --check
        - setup.py
        - genomepy/
        - tests/

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear==21.4.3
      args:
        - setup.py
        - genomepy/
        - tests/
