channels:
  - conda-forge
  - bioconda
dependencies:
  - docutils =0.17.1  # 18 & 19 bugs: no bullet lists & sub-menus
  - sphinx
  - sphinx_rtd_theme  # read the docs theme
  - m2r2 >=0.3.2      # include markdown files
